name: deploy

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: cache notebook
        uses: actions/cache@v3
        with:
          path: _build/.jupyter_cache
          key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

      - name: Build the book
        run: jupyter-book build presentation/lab-1/test.ipynb

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "_build/html"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2