name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "presentation/lab-2/build/"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
